-- DROP TABLE account;
-- DROP TABLE image;
CREATE TABLE IF NOT EXISTS image (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title varchar(255) NULL,
    url varchar(255) NULL,
    CONSTRAINT image_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS account (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    active bool NOT NULL,
    "password" varchar(255) NULL,
    "role" int NULL,
    username varchar(255) NULL,
    current_img_id int8 NULL,
    CONSTRAINT account_pkey PRIMARY KEY (id),
    CONSTRAINT uk_gex1lmaqpg0ir5g1f5eftyaa1 UNIQUE (username),
    CONSTRAINT fkjh17cr8hbm3s73ijxp4whya5x FOREIGN KEY (current_img_id) REFERENCES image(id)
);
CREATE TABLE IF NOT EXISTS account_images (
    user_id int NOT NULL,
    images_id int NOT NULL,
    CONSTRAINT uk_2xxeitsasdia8hxig2we8wfr7 UNIQUE (images_id),
    CONSTRAINT fk9a0e8otj3rxo4hworcgvi5d4s FOREIGN KEY (user_id) REFERENCES account(id),
    CONSTRAINT fkn9079lcjx6bmfctlnm3rxcvpf FOREIGN KEY (images_id) REFERENCES image(id)
);

INSERT INTO account(active, password, role, username)
VALUES (true, '$2y$12$GqWvfez7rD6/cGhqZ0XmN.y5FFmHLqeuc7v5ZWAzG6Xu6gLKNuvUq',0, 'kenneth'),
(true, '$2y$12$cGpBWUOT1.kXQRIDP4XCm.A45LxoKaHvRz6f/pO96d5FKZ2sAuwGy', 0, 'martin'),
(true, '$2y$12$XUdjpXjbIeH/lw/r7m9ROeOPYRVwdsLZ2WgtHX1.tIOrTPyZXbxmG', 0, 'simon'),
(true, '$2y$12$uHPlqlcGAq7Kxu/H47Ont./XDPcZkAsHbSLWLWkof7JfmvMMQZpKy', 0, 'frederik')
ON CONFLICT DO NOTHING