-- DROP TABLE account;
-- DROP TABLE image;


CREATE TABLE IF NOT EXISTS image (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    filename varchar(255) NULL,
    title varchar(255) NULL,
    url varchar(255) NULL,
    CONSTRAINT image_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS account (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    active bool NOT NULL,
    "password" varchar(255) NULL,
    "role" int NULL,
    username varchar(255) NULL,
    current_img_id int8 NULL,
    CONSTRAINT account_pkey PRIMARY KEY (id),
    CONSTRAINT uk_gex1lmaqpg0ir5g1f5eftyaa1 UNIQUE (username),
    CONSTRAINT fkjh17cr8hbm3s73ijxp4whya5x FOREIGN KEY (current_img_id) REFERENCES image(id)
);
CREATE TABLE IF NOT EXISTS account_images (
    user_id int NOT NULL,
    images_id int NOT NULL,
    CONSTRAINT uk_2xxeitsasdia8hxig2we8wfr7 UNIQUE (images_id),
    CONSTRAINT fk9a0e8otj3rxo4hworcgvi5d4s FOREIGN KEY (user_id) REFERENCES account(id),
    CONSTRAINT fkn9079lcjx6bmfctlnm3rxcvpf FOREIGN KEY (images_id) REFERENCES image(id)
);